name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK with buildozer-action
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .

      - name: Upload artifact (APK)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
