name: Build APK

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .  # المجلد الجذر (حيث main.py و buildozer.spec)
          buildozer_version: stable
          command: buildozer -v android debug  # أمر البناء الافتراضي

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ${{ steps.buildozer.outputs.filename }}
