# .github/workflows/build.yml
name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build APK with buildozer-action
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          # لا تُمرّر python-version هنا إذا استخدمت setup-python أعلاه

      - name: Upload artifact (APK)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
