name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # اضبط هنا python-version إلى 3.10 (لم يكن 3.1)
      - name: Build APK with buildozer-action
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.10
          buildozer-cmd: buildozer -v android debug

      - name: Upload artifact (APK)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
